name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  # Unit Tests
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Run tests in Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn test

  # e2e Tests
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Cypress Run
        uses: cypress-io/github-action@v2
        with:
          start: yarn run start
          browser: chrome
          headless: true
          wait-on: http://localhost:3000
          wait-on-timeout: 120
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          CYPRESS_TEST_UID: ${{ secrets.TEST_UID }}
          CYPRESS_FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          GITHUB_REF: ${{ github.ref }}
        